# Site settings
title: David | NYC
description: David | NYC
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: davidtskaggs.github.io
dbc_url: devbootcamp.com

# User settings
username: David Skaggs
location: New York City
user_title: Full Stack Developer
user_description: David is a 2017 graduate of Dev Bootcamp in New York City, where he was immersered in FullStack Web Development. At Dev Bootcamp, David crafted an art and appreciation for not only making things look pretty on the front-end but diving deep into the back-end to set-up databases properly. Before Dev Bootcamp, David's career focused on the client-side various SaaS companies, where he gained invaluable customer service skills and technical insights. David holds a bachelor's degree in Political Science from College of Charleston and a Web Development Certification from Dev Bootcamp. 
email: davidtskaggs@gmail.com
twitter_username: dtskaggs
github_username:  davidtskaggs
gplus_username:  davidtskaggs

# Google-analytics
google-analytics:
  id: "UA-111364017-1"

exclude: ['package.json', 'src' , 'node_modules']
