# Site settings
title: David | NYC
description: David | NYC
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: davidtskaggs.github.io

# User settings
username: David Skaggs
location: New York City
user_title: Full Stack Developer
user_description: David is a 2017 graduate of Dev Bootcamp in New York City, where he was immersered in FullStack Development. Before Dev, David gained invaluable customer service skills and technical insights while working directly with customers at various SaaS companies. David holds a bachlors degree in Political Science from College of Charleston.
email: davidtskaggs@gmail.com
twitter_username: dtskaggs
github_username:  davidtskaggs
gplus_username:  davidtskaggs

# Google-analytics
google-analytics:
  id: "UA-111364017-1"

exclude: ['package.json', 'src' , 'node_modules']
